### ISSUE TITLE
problem with building the project

### ISSUE THREAD

**Issue by SantoCovato** [fbiego/dt78-esp32-firmware#1]
Hi, I just tried to build my project to try on my microcontroller, but visual studio give me this error: A fatal error occurred: This chip is ESP32-S3 not ESP32. Wrong --chip argument?
*** [upload] Error 2
so the problem is, can I use this project for my esp32-s3? 
thanks for the answer in andvance

**Comment by fbiego** [comment]
You need to change the line below and configure the correct board
https://github.com/fbiego/dt78-esp32-firmware/blob/750739d03cb232f682c9b4b6234c2c92b4d176d9/platformio.ini#L13

**Comment by SantoCovato** [comment]
oh ok, thank you
